export const DISPOSITIONS_LOADED = "DISPOSITIONS_LOADED";
export const DISPOSITION_TYPES_LOADED = "DISPOSITION_TYPES_LOADED";
export const DISPOSITION_CATEGORIES_LOADED = "DISPOSITION_CATEGORIES_LOADED";

export const CATEGORY_COLORS = {
    0: "GREEN",
    2: "yellow",
    1: "LIGHT_RED",
}