export const DISPOSITION_CATEGORIES_LOADED = "DISPOSITION_CATEGORIES_LOADED";
export const DISPOSITION_NOTES_LOADED = "DISPOSITION_NOTES_LOADED";
export const AGENT_PHONE_STATUS = "AGENT_PHONE_STATUS";